### ISSUE TITLE
Add link to the website in repository description

### ISSUE THREAD

**Issue by bocharsky-bw** [Happyr/developer.happyr.com#4]
Also, add a link to http://developer.happyr.com , now I see description only:

<img width="1001" alt="screen shot 2018-01-15 at 14 01 13" src="https://user-images.githubusercontent.com/3317635/34941502-a9943908-f9fc-11e7-9704-48432f0a349d.png">

**Comment by Nyholm** [comment]
Haha, you are too quick. 

I added this a few hours ago and then went to lunch. 

Thank you!

**Comment by bocharsky-bw** [comment]
haha, I am :D 

P.S. you probably add the link to the Description field instead of Website, so it's not clickable right now :/
